### ISSUE TITLE
#spawn tests fail on newer web3 versions

### ISSUE THREAD

**Issue by jtobin** [urbit/azimuth-js#62]
Most of our deps are specified in the `^x.y.z` format, which allows npm to upgrade to any semver-compatible version at its leisure.  It looks like some dependency breaks subtly on upgrade, though, since the `generates usable transaction` test fails with a length of 255 instead of the expected 253.

I discovered this while doing a plain `npm install` to update dependencies.  I wasn't in the mood to figure out exactly what caused the problem, though, so until I am, I've just manually knocked the dependencies back to what's specified by a working lockfile.

**Comment by Fang-** [comment]
For one thing, [as per the mailing list](https://groups.google.com/a/urbit.org/g/dev/c/XEIBEvCGe14/m/RZXOXGtDCgAJ), ethereumjs-utils changed their library structure around a little bit.

**Comment by jtobin** [comment]
I'm not sure if this is still relevant, or if it is it's likely not specific enough.  I bumped azimuth-solidity, Truffle, ganache, and mocha earlier, and there was the bump to ethereumjs-util earlier today as well.  So that's quite a few new dependency versions, with no problem for the spawn tests on my end.

**Comment by jtobin** [comment]
I looked into this a bit and it appears the culprit is (no surprise) web3.  The other dependencies can be upgraded without causing any issue.

**Comment by ghost** [comment]
I modestly suggest perhaps a transition to ethers as it is relatively well known to be more sanely maintained with less breaking changes than web3. I could help with this.

**Comment by jtobin** [comment]
Oh, interesting!  I actually had never heard of ethers; I don't need much convincing that it's probably a better library.

I think the only problem I can see with switching is that the burden of the migration would seemingly fall on users.  I.e., I'm not sure we could just do a bunch of heavy work here and have people upgrade without any real effort downstream, where presumably they're already making some use of web3.

(It might depend on how much @Fang- wants to use ethers in [Bridge](https://github.com/urbit/bridge). 😄)

**Comment by ghost** [comment]
yeah, it's definitely possible, but I'm not too sure we'd actually run into any issues with breaking things with users. I think the only case where users' usage of azimuth-js is mixed also with the users' own usage of web3/ethers is when the tx is constructed and sent with a web3 provider that doesn't directly have the private keys (like the FakeMetamask pattern used in bridge) and web3 uses ethers' abicoder anyway now, and the JSON/js object representation of unsigned tx is the same and is a part of the eth rpc standard itself.

re: bridge, I'd guess it would actually continue working with the mixed usage, but looked thru and I don't think it'd be too much to work to migrate over. I'd be willing to do the migration there, but I don't think it's immediately necessary.

it's fine either way for me, but a small anecdote which slightly inclines me to devote myself to this change(esp in light of recent package issues): one time I spent approximately 10 hours running yarn install and yarn add of various packages in different magical orders before I finally got a yarn.lock that had various web3 libraries to successfully deploy on heroku because the branch had had several package installed since its common ancestor with the last deployment

EDIT: after taking a look, there might be a minor issue with our current style of passing web3 down from initContracts. it looks like web3 object injected from browser is commonly a proxy, we use our own in bridge, but others might not be. so obj.constructor.name would not be sufficient to distinguish web3 vs something which implements ethers' Provider interface. it can probably be done another way, though. generally, with the change, we'd be passing something that implements ethers' Provider, but we might want to support web3 directly. or, we pass a small breaking change where people need to pass new Web3Provider(web3) (implements ethers' Provider class, gets ethers' Provider from web3 object)

EDIT2: looks like one could do `if('currentProvider' in provider)` to detect if someone passed in a web3 object and thus avoid breaking changes

EDIT3: ethers uses different BigNumber for its args and return values, might be a source of breaking changes here, so maybe not worth it(but maybe not an issue at all, or at least in most cases, azimuth points are uint32 which I don't think get de/encoded as bignumber)

**Comment by Fang-** [comment]
> ethers uses different BigNumber for its args and return values, might be a source of breaking changes here, so maybe not worth it

This spooks the hell out of me lol.

I don't keep up with Ethereum development environment things, so I'd trust @xiphiness' judgement on what's good these days over my own. Breaking changes aren't very nice, but this is what semver exists for, right? My main concern is potential Bridge-side work and pulling in something new, neither of which I have the time for (to fully stay in touch with). If you want to take more ownership over both these things, we can discuss that, but I'd still err on the side of being conservative.

Hit me up to talk about this, if you want. I'll try and think about this a little bit, try and figure out what attitude is most appropriate for these kinds of things.

**Comment by ghost** [comment]
https://github.com/xiphiness/azimuth-js/tree/ethers here's a less breaking version with ethers that I only had to change a few things for in bridge. the main thing is if ppl are interacting with the object that has the contracts themselves the e.g. events API is different.

there's another way I would do it that is more breaking, but in my opinion better.

I'd use typechain to make all the contracts typed & do it all in typescript

also I'd remove the signing functionality entirely and just instruct people to use ethers' Signer abstract class (can pull from PK or create one out of metamask or whatever)

usage would be add a provider or signer into the initContracts, the default exported not on contract class methods exports the calldata building methods, if you add a signer you can call the write functions directly on the contracts.
